/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyntaxGuideRouteImport } from './routes/syntax-guide'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as BenchmarkRouteImport } from './routes/benchmark'
import { Route as IndexRouteImport } from './routes/index'

const SyntaxGuideRoute = SyntaxGuideRouteImport.update({
  id: '/syntax-guide',
  path: '/syntax-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarkRoute = BenchmarkRouteImport.update({
  id: '/benchmark',
  path: '/benchmark',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/benchmark': typeof BenchmarkRoute
  '/playground': typeof PlaygroundRoute
  '/syntax-guide': typeof SyntaxGuideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/benchmark': typeof BenchmarkRoute
  '/playground': typeof PlaygroundRoute
  '/syntax-guide': typeof SyntaxGuideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/benchmark': typeof BenchmarkRoute
  '/playground': typeof PlaygroundRoute
  '/syntax-guide': typeof SyntaxGuideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/benchmark' | '/playground' | '/syntax-guide'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/benchmark' | '/playground' | '/syntax-guide'
  id: '__root__' | '/' | '/benchmark' | '/playground' | '/syntax-guide'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenchmarkRoute: typeof BenchmarkRoute
  PlaygroundRoute: typeof PlaygroundRoute
  SyntaxGuideRoute: typeof SyntaxGuideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/syntax-guide': {
      id: '/syntax-guide'
      path: '/syntax-guide'
      fullPath: '/syntax-guide'
      preLoaderRoute: typeof SyntaxGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmark': {
      id: '/benchmark'
      path: '/benchmark'
      fullPath: '/benchmark'
      preLoaderRoute: typeof BenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenchmarkRoute: BenchmarkRoute,
  PlaygroundRoute: PlaygroundRoute,
  SyntaxGuideRoute: SyntaxGuideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
